### ISSUE TITLE
ClockReplacer : There is no limit on the maximum number of pages in the clockreplacer. 

### ISSUE THREAD

**Issue by gaofanfei** [duynguyen-ori75/bustub#2]

**Comment by duynguyen-ori75** [comment]
I am not sure what you described.

The clock replacer needs a fixed number of pages in order to function correctly.

More about the algorithm can be found here:

https://www.geeksforgeeks.org/second-chance-or-clock-page-replacement-policy/

**Comment by gaofanfei** [comment]
> The size of the ClockReplacer is the same as buffer pool since it contains placeholders for all of the frames in the BufferPoolManager. However, not all the frames are considered as in the ClockReplacer.

The constructor of ClockReplacer has an  argument `size_t num_pages`, I think this is the maximum numbers of pages we can put into the ClockReplacer. But it seems that you don't limit the number of page in your clockreplacer.

**Comment by duynguyen-ori75** [comment]
You can think that `size_t num_pages` is the maximum number of pages that the replacer can hold.

To be precise, `num_pages` is the number of frames that the buffer pool manager is managing. The replacer is an internal data structure of the BPM, which helps it determine which page should be evicted next.

https://15445.courses.cs.cmu.edu/fall2019/slides/05-bufferpool.pdf

I would say that if you are going to implement a data structure holding a dynamic number of elements (here is the frame), feel free to do so. My decision was to implement a data structure with a fixed number of elements and put null elements to un-used slots (there are many ways to achieve this). Different approaches but the targets are the same. 

You may want to check the replacer tests and understand how it works under the hood.
